### ISSUE TITLE
Settings page for lazy loading parameters on Firefox does not work

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix-svelte-frontend#272] opened 2020-10-10 10:53 UTC
Firefox can't render the lazy loading input fields, it seems. Furthermore you can't close the window via the X.

**Comment by mosheduminer** [comment] 2020-10-11 23:14
It sounds like there is an error causing the application to crash, which is why the window could not be closed afterward. This needs further investigation.

**Comment by mosheduminer** [comment] 2020-10-16 14:42
I tested on firefox (on linux), and was unable to reproduce the problem. I am closing this issue, feel free to reopen if the issue persists.

**Closed by mosheduminer** 2020-10-16 14:42 UTC
Labels: bug, hacktoberfest
